server:
  port: 8080

spring:
  application:
    name: influxdb3-demo
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML

# InfluxDB v3 配置示例
# 请根据您的InfluxDB实例修改以下配置
influxdb:
  # InfluxDB服务器地址
  url: http://localhost:8086
  
  # API Token - 请替换为您的实际Token
  # 在InfluxDB UI中: Data > API Tokens > Generate API Token
  token: your-influxdb-token-here
  
  # 组织名称 - 请替换为您的组织名称
  # 在InfluxDB UI中: Settings > Organizations
  org: your-organization
  
  # 存储桶名称 - 请替换为您的存储桶名称
  # 在InfluxDB UI中: Data > Buckets
  bucket: your-bucket
  
  # 数据库名称 (可选，用于向后兼容)
  database: your-database

# 日志配置
logging:
  level:
    # 应用日志级别
    com.example.influxdb3demo: DEBUG
    
    # InfluxDB客户端日志级别
    com.influxdb: DEBUG
    
    # Spring框架日志级别
    org.springframework: INFO
    
    # 根日志级别
    root: INFO
  
  # 日志输出格式
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  
  # 日志文件配置 (可选)
  file:
    name: logs/influxdb3-demo.log
    max-size: 10MB
    max-history: 30

# 开发环境配置
spring:
  profiles:
    active: dev
  
  # 开发工具配置
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# 生产环境配置示例
---
spring:
  config:
    activate:
      on-profile: prod
  
  # 生产环境禁用开发工具
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

# 生产环境日志配置
logging:
  level:
    com.example.influxdb3demo: INFO
    com.influxdb: WARN
    org.springframework: WARN
    root: WARN 